services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database-api
    environment:
      - DATABASE_API_URL=http://database-api:8000
      - SECRET_KEY=your-super-secret-key-123
      - FLASK_ENV=production
    volumes:
      - .:/app
    command: python app.py

  database-api:
    build:
      context: .
      dockerfile: Dockerfile.database
    ports:
      - "8000:8000"
    volumes:
      - ./guardiantix.db:/data/guardiantix.db
    environment:
      - SECRET_KEY=your-super-secret-key-123